"""NetworkX type stubs for DiGraph"""

from collections.abc import Iterable
from typing import Any

class DiGraph:
    """NetworkX DiGraph type stub"""
    def degree(self, node: Any) -> int: ...
    def neighbors(self, node: Any) -> Iterable[Any]: ...
    def in_degree(self, node: Any) -> int: ...
    def out_degree(self, node: Any) -> int: ...
    def nodes(self) -> Iterable[Any]: ...
