"""
NetworkX type stubs for AgentDev
"""

from collections.abc import Iterator
from typing import Any

# Type aliases for NetworkX views
NodeView = set[str]
EdgeView = set[tuple[str, str]]
DiDegreeView = dict[str, int]
OutDegreeView = dict[str, int]
InDegreeView = dict[str, int]

class DiGraph:
    def __init__(self) -> None: ...
    def add_node(self, node_for_adding: str, **attr: Any) -> None: ...
    def add_edge(self, u_of_edge: str, v_of_edge: str, **attr: Any) -> None: ...
    def nodes(self) -> NodeView: ...
    def edges(self) -> EdgeView: ...
    def degree(self, node: str) -> int: ...
    def in_degree(self, node: str) -> int: ...
    def out_degree(self, node: str) -> int: ...
    def number_of_nodes(self) -> int: ...
    def number_of_edges(self) -> int: ...
    def has_node(self, node: str) -> bool: ...
    def has_edge(self, u: str, v: str) -> bool: ...
    def neighbors(self, node: str) -> Iterator[str]: ...
    def successors(self, node: str) -> Iterator[str]: ...
    def predecessors(self, node: str) -> Iterator[str]: ...
