"""
Schedule library type stubs for AgentDev
"""

from collections.abc import Callable
from typing import Any

class Job:
    def do(self, job_func: Callable[..., Any]) -> Job: ...

class Every:
    def minutes(self) -> Job: ...
    def hours(self) -> Job: ...
    def day(self) -> Job: ...
    def at(self, time: str) -> Job: ...

def every(interval: int = 1) -> Every: ...
