#!/usr/bin/env python3
"""
Setup script for StillMe Email Notifications
"""

import os
import sys
from pathlib import Path


def create_env_file():
    """Create .env file for email notifications"""
    print("🔧 Setting up Email Notifications...")
    
    # Check if .env already exists
    env_file = Path(".env")
    if env_file.exists():
        print("⚠️ .env file already exists. Backing up to .env.backup")
        env_file.rename(".env.backup")
    
    # Get user input
    print("\n📧 Email Configuration:")
    smtp_username = input("Enter your Gmail address: ").strip()
    smtp_password = input("Enter your Gmail App Password (16 characters): ").strip()
    alert_email = input("Enter alert email address (default: same as Gmail): ").strip() or smtp_username
    
    print("\n📱 Optional SMS Configuration (press Enter to skip):")
    twilio_sid = input("Twilio Account SID: ").strip()
    twilio_token = input("Twilio Auth Token: ").strip()
    twilio_phone = input("Twilio Phone Number (+1234567890): ").strip()
    alert_phone = input("Alert Phone Number (+84901234567): ").strip()
    
    print("\n💬 Optional Slack Configuration (press Enter to skip):")
    slack_webhook = input("Slack Webhook URL: ").strip()
    slack_channel = input("Slack Channel (#alerts): ").strip() or "#alerts"
    
    # Create .env content
    env_content = f"""# StillMe Email Notification Configuration
# Generated by setup_email_notifications.py

# Email Settings (Gmail)
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME={smtp_username}
SMTP_PASSWORD={smtp_password}
ALERT_EMAIL={alert_email}

# Email Display Settings
EMAIL_FROM_NAME=StillMe AI System
EMAIL_FROM_EMAIL={smtp_username}
EMAIL_REPLY_TO={smtp_username}

# Email Security Settings
EMAIL_USE_TLS=true
EMAIL_USE_SSL=false
EMAIL_TIMEOUT=30
EMAIL_MAX_RETRIES=3

# SMS Settings (Twilio - Optional)
TWILIO_ACCOUNT_SID={twilio_sid}
TWILIO_AUTH_TOKEN={twilio_token}
TWILIO_PHONE_NUMBER={twilio_phone}
ALERT_PHONE={alert_phone}

# Slack Settings (Optional)
SLACK_WEBHOOK_URL={slack_webhook}
SLACK_CHANNEL={slack_channel}

# Telegram Settings (Optional)
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# Notification Settings
ESCALATION_ENABLED=true
ESCALATION_TIMEOUT_MINUTES=15
MAX_RETRIES=3

# VPS Settings
VPS_IP=160.191.89.99
VPS_USERNAME=root
VPS_PASSWORD=
"""
    
    # Write .env file
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("✅ .env file created successfully!")
    return True


def show_gmail_setup_instructions():
    """Show Gmail App Password setup instructions"""
    print("\n📋 Gmail App Password Setup Instructions:")
    print("=" * 50)
    print("1. Go to https://myaccount.google.com/security")
    print("2. Enable 2-Factor Authentication (if not already enabled)")
    print("3. Go to 'App passwords' section")
    print("4. Click 'Generate new password'")
    print("5. Select 'Mail' and 'Other'")
    print("6. Enter 'StillMe VPS Notifications' as the name")
    print("7. Copy the 16-character password")
    print("8. Use this password in the setup (not your regular Gmail password)")
    print("=" * 50)


def show_twilio_setup_instructions():
    """Show Twilio setup instructions"""
    print("\n📱 Twilio SMS Setup Instructions:")
    print("=" * 50)
    print("1. Go to https://www.twilio.com/")
    print("2. Sign up for a free account")
    print("3. Get your Account SID and Auth Token from the dashboard")
    print("4. Buy a phone number (free trial includes $15 credit)")
    print("5. Use the phone number in the format +1234567890")
    print("=" * 50)


def show_slack_setup_instructions():
    """Show Slack webhook setup instructions"""
    print("\n💬 Slack Webhook Setup Instructions:")
    print("=" * 50)
    print("1. Go to your Slack workspace")
    print("2. Go to Apps → Incoming Webhooks")
    print("3. Click 'Add to Slack'")
    print("4. Choose the channel for alerts")
    print("5. Copy the webhook URL")
    print("=" * 50)


def main():
    """Main setup function"""
    print("🚀 StillMe Email Notification Setup")
    print("=" * 50)
    
    # Check if we're in the right directory
    if not Path("stillme_platform").exists():
        print("❌ Please run this script from the project root directory")
        sys.exit(1)
    
    # Show setup instructions
    show_gmail_setup_instructions()
    
    # Ask if user wants to continue
    continue_setup = input("\nDo you want to continue with the setup? (y/n): ").strip().lower()
    if continue_setup != 'y':
        print("Setup cancelled.")
        return
    
    # Create .env file
    if create_env_file():
        print("\n✅ Email notification setup completed!")
        print("\n📋 Next steps:")
        print("1. Test the email notifications: python test_email_notifications.py")
        print("2. Check your email for test messages")
        print("3. If successful, the notification system is ready!")
        
        # Ask about optional services
        print("\n🔧 Optional Services:")
        setup_sms = input("Do you want to setup SMS notifications? (y/n): ").strip().lower()
        if setup_sms == 'y':
            show_twilio_setup_instructions()
        
        setup_slack = input("Do you want to setup Slack notifications? (y/n): ").strip().lower()
        if setup_slack == 'y':
            show_slack_setup_instructions()
        
        print("\n🎉 Setup complete! You can now test the notification system.")
    else:
        print("❌ Setup failed. Please try again.")


if __name__ == "__main__":
    main()
