# AgentDev DAG Schema - SEAL-GRADE
# Enterprise-grade workflow definition schema

# DAG Definition
dag:
  name: "agentdev_workflow"
  version: "1.0.0"
  description: "AgentDev workflow orchestration"
  author: "StillMe AI"
  created_at: "2025-01-23"
  
  # Global settings
  settings:
    max_concurrent_tasks: 10
    timeout_seconds: 3600
    retry_policy:
      max_retries: 3
      retry_delay: 5
      exponential_backoff: true
    failure_policy: "stop_on_first_failure"  # stop_on_first_failure, continue_on_failure
    success_policy: "all_tasks_success"      # all_tasks_success, any_task_success
    
    # Caching
    cache:
      enabled: true
      ttl_seconds: 3600
      key_strategy: "task_input_hash"  # task_input_hash, task_name, custom
    
    # Resource limits
    resources:
      max_memory_mb: 2048
      max_cpu_percent: 80
      max_disk_mb: 1024

# Node Definitions
nodes:
  # Job Management Nodes
  job_start:
    type: "job_management"
    task: "start_job"
    description: "Initialize job execution"
    inputs:
      job_id: "string"
      user_id: "string"
      session_id: "string"
    outputs:
      job_context: "object"
      start_time: "timestamp"
    retry_policy:
      max_retries: 1
      retry_delay: 2
    timeout_seconds: 30
    cache:
      enabled: false
    
  job_complete:
    type: "job_management"
    task: "complete_job"
    description: "Finalize job execution"
    inputs:
      job_id: "string"
      status: "string"
      results: "object"
    outputs:
      completion_time: "timestamp"
      final_status: "string"
    retry_policy:
      max_retries: 2
      retry_delay: 5
    timeout_seconds: 60
    cache:
      enabled: false
  
  # AI Processing Nodes
  ai_request:
    type: "ai_processing"
    task: "make_ai_request"
    description: "Make AI model request"
    inputs:
      prompt: "string"
      model: "string"
      parameters: "object"
    outputs:
      response: "string"
      tokens_used: "integer"
      latency_ms: "integer"
    retry_policy:
      max_retries: 3
      retry_delay: 10
    timeout_seconds: 120
    cache:
      enabled: true
      ttl_seconds: 1800
      key_strategy: "task_input_hash"
    
  ai_response_processing:
    type: "ai_processing"
    task: "process_ai_response"
    description: "Process and validate AI response"
    inputs:
      response: "string"
      validation_rules: "array"
    outputs:
      processed_response: "string"
      validation_status: "string"
      confidence_score: "float"
    retry_policy:
      max_retries: 2
      retry_delay: 3
    timeout_seconds: 30
    cache:
      enabled: true
      ttl_seconds: 900
  
  # Tool Execution Nodes
  tool_execution:
    type: "tool_execution"
    task: "execute_tool"
    description: "Execute a specific tool"
    inputs:
      tool_name: "string"
      parameters: "object"
      security_context: "object"
    outputs:
      result: "object"
      execution_time_ms: "integer"
      status: "string"
    retry_policy:
      max_retries: 2
      retry_delay: 5
    timeout_seconds: 300
    cache:
      enabled: true
      ttl_seconds: 600
      key_strategy: "custom"
      custom_key: "tool_name + parameters_hash"
  
  # Security Nodes
  security_validation:
    type: "security"
    task: "validate_security"
    description: "Validate security policies"
    inputs:
      request_data: "object"
      security_policies: "array"
    outputs:
      validation_result: "object"
      security_score: "float"
      blocked: "boolean"
    retry_policy:
      max_retries: 1
      retry_delay: 2
    timeout_seconds: 15
    cache:
      enabled: true
      ttl_seconds: 300
  
  # Data Processing Nodes
  data_transformation:
    type: "data_processing"
    task: "transform_data"
    description: "Transform input data"
    inputs:
      input_data: "object"
      transformation_rules: "array"
    outputs:
      transformed_data: "object"
      transformation_metadata: "object"
    retry_policy:
      max_retries: 2
      retry_delay: 3
    timeout_seconds: 60
    cache:
      enabled: true
      ttl_seconds: 1200
  
  # Monitoring Nodes
  health_check:
    type: "monitoring"
    task: "check_health"
    description: "Check system health"
    inputs:
      check_services: "array"
    outputs:
      health_status: "object"
      unhealthy_services: "array"
    retry_policy:
      max_retries: 1
      retry_delay: 5
    timeout_seconds: 30
    cache:
      enabled: true
      ttl_seconds: 60
  
  # Custom Nodes
  custom_processing:
    type: "custom"
    task: "custom_task"
    description: "Custom processing task"
    inputs:
      custom_input: "object"
    outputs:
      custom_output: "object"
    retry_policy:
      max_retries: 3
      retry_delay: 5
    timeout_seconds: 180
    cache:
      enabled: false

# Edge Definitions (Dependencies)
edges:
  # Job lifecycle edges
  - from: "job_start"
    to: "security_validation"
    condition: "always"
    weight: 1
    
  - from: "security_validation"
    to: "ai_request"
    condition: "security_passed"
    weight: 1
    
  - from: "ai_request"
    to: "ai_response_processing"
    condition: "ai_success"
    weight: 1
    
  - from: "ai_response_processing"
    to: "tool_execution"
    condition: "processing_success"
    weight: 1
    
  - from: "tool_execution"
    to: "data_transformation"
    condition: "tool_success"
    weight: 1
    
  - from: "data_transformation"
    to: "job_complete"
    condition: "transformation_success"
    weight: 1
    
  # Monitoring edges
  - from: "job_start"
    to: "health_check"
    condition: "always"
    weight: 0.5
    
  - from: "health_check"
    to: "job_complete"
    condition: "health_ok"
    weight: 0.5
    
  # Error handling edges
  - from: "security_validation"
    to: "job_complete"
    condition: "security_failed"
    weight: 1
    error_handling: true
    
  - from: "ai_request"
    to: "job_complete"
    condition: "ai_failed"
    weight: 1
    error_handling: true
    
  - from: "tool_execution"
    to: "job_complete"
    condition: "tool_failed"
    weight: 1
    error_handling: true

# Conditional Logic
conditions:
  security_passed:
    type: "expression"
    expression: "validation_result.blocked == false"
    
  security_failed:
    type: "expression"
    expression: "validation_result.blocked == true"
    
  ai_success:
    type: "expression"
    expression: "response != null && response != ''"
    
  ai_failed:
    type: "expression"
    expression: "response == null || response == ''"
    
  processing_success:
    type: "expression"
    expression: "validation_status == 'valid'"
    
  tool_success:
    type: "expression"
    expression: "status == 'success'"
    
  tool_failed:
    type: "expression"
    expression: "status == 'failed'"
    
  transformation_success:
    type: "expression"
    expression: "transformed_data != null"
    
  health_ok:
    type: "expression"
    expression: "health_status.overall == 'healthy'"
    
  always:
    type: "constant"
    value: true

# Workflow Templates
templates:
  simple_ai_workflow:
    description: "Simple AI request workflow"
    nodes: ["job_start", "ai_request", "ai_response_processing", "job_complete"]
    edges:
      - from: "job_start"
        to: "ai_request"
      - from: "ai_request"
        to: "ai_response_processing"
      - from: "ai_response_processing"
        to: "job_complete"
  
  secure_tool_workflow:
    description: "Secure tool execution workflow"
    nodes: ["job_start", "security_validation", "tool_execution", "job_complete"]
    edges:
      - from: "job_start"
        to: "security_validation"
      - from: "security_validation"
        to: "tool_execution"
        condition: "security_passed"
      - from: "tool_execution"
        to: "job_complete"
      - from: "security_validation"
        to: "job_complete"
        condition: "security_failed"
        error_handling: true
  
  full_processing_workflow:
    description: "Full data processing workflow"
    nodes: ["job_start", "security_validation", "ai_request", "ai_response_processing", "tool_execution", "data_transformation", "job_complete"]
    edges:
      - from: "job_start"
        to: "security_validation"
      - from: "security_validation"
        to: "ai_request"
        condition: "security_passed"
      - from: "ai_request"
        to: "ai_response_processing"
        condition: "ai_success"
      - from: "ai_response_processing"
        to: "tool_execution"
        condition: "processing_success"
      - from: "tool_execution"
        to: "data_transformation"
        condition: "tool_success"
      - from: "data_transformation"
        to: "job_complete"
        condition: "transformation_success"
      - from: "security_validation"
        to: "job_complete"
        condition: "security_failed"
        error_handling: true
      - from: "ai_request"
        to: "job_complete"
        condition: "ai_failed"
        error_handling: true
      - from: "tool_execution"
        to: "job_complete"
        condition: "tool_failed"
        error_handling: true

# Validation Rules
validation:
  required_fields:
    - "dag.name"
    - "dag.version"
    - "nodes"
    - "edges"
  
  node_validation:
    required_fields:
      - "type"
      - "task"
      - "description"
    allowed_types:
      - "job_management"
      - "ai_processing"
      - "tool_execution"
      - "security"
      - "data_processing"
      - "monitoring"
      - "custom"
  
  edge_validation:
    required_fields:
      - "from"
      - "to"
    validate_nodes_exist: true
    validate_conditions_exist: true
  
  cycle_detection: true
  orphan_node_detection: true
  unreachable_node_detection: true
